-- Таблица пользователей
create table users (
    user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(50) UNIQUE NOT NULL,
    login varchar(50) UNIQUE NOT NULL,
    name varchar(50),
    birth_day DATE CHECK (birth_day <= CURRENT_DATE)
);
-- Таблица рейтингов
create table ratings (
    rating_id SMALLINT PRIMARY KEY,
    name varchar(10) UNIQUE NOT NULL
);

INSERT INTO rating VALUES
(1, 'G'),
(2, 'PG'),
(3, 'PG-13'),
(4, 'R'),
(5, 'NC-17');

-- Таблица фильмов
create table films (
    film_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(200) NOT NULL,
    description text,
    release_date DATE NOT NULL,
    duration INTERVAL NOT NULL,
    rating_id int REFERENCES ratings (rating_id)
);



-- Таблица лайков фильмов
create table film_likes (
    user_id bigint REFERENCES users (user_id),
    film_id bigint REFERENCES films (film_id),
    PRIMARY KEY (user_id, film_id)
);

-- Таблица жанров
create table genre (
    genre_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) UNIQUE NOT NULL
);

-- Таблица связи фильмов и жанров
create table film_genre (
    film_id bigint REFERENCES films (film_id),
    genre_id int REFERENCES genre (genre_id),
    PRIMARY KEY (film_id, genre_id)
);

-- Таблица друзей
create table friends (
    user_id bigint REFERENCES users (user_id),
    friend_id bigint REFERENCES users (user_id),
    confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (user_id, friend_id)
);
